### PR TITLE
nightly.sh: add flag to set Hugging Face token

### LINKED ISSUE #6401: [torchbench] HF API Token for benchmark execution.
## 🐛 Bug

Some benchmarks are not working (internally) because PyTorch/benchmark expects `HUGGING_FACE_HUB_TOKEN` environment variable (HF API token) to be set:

```python
NotImplementedError: Make sure to set `HUGGING_FACE_HUB_TOKEN` so you can download weights
```

## Affected Benchmarks

- stable_diffusion_text_encoder
- stable_diffusion_unet
- llama_v2_7b_16h

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CUDA
 - torch_xla version: 9e4db963a196378e7e812bcb58f8f1af6a8f452f

cc @miladm @JackCaoG @cota @frgossen

### PR DESCRIPTION
**Pull request by cota**
Fixes #6401.

### CODE REVIEW

File: benchmarks/nightly.sh [hunk 1]
```diff
@@ -24,6 +24,12 @@ do
     R)
       REPEAT=${OPTARG:?}
       ;;
+    T)
+      # Avoid printing the token; re-enable printing later.
+      { set +x; } 2>/dev/null
```
Comment (frgossen) [inline benchmarks/nightly.sh:29]: Does it really print the token otherwise?

**Review by frgossen — APPROVED** [review]
Nice! Ty!

File: benchmarks/nightly.sh (hunk 1 above)
Comment (cota) [reply benchmarks/nightly.sh:29]: It really does :)
With `set -x` every bash command gets printed out -- `FOO=BAR` (i.e. bash variable assignment) or `export FOO=BAR` both get printed out.
For good measure I'm also stripping out the token from the logs/json files in case it ever leaks out of this script or through the Torchbench logs.

Comment (frgossen) [reply benchmarks/nightly.sh:29]: Thanks for checking

**Review by golechwierowicz — APPROVED** [review]
So this is supposed to make llama v2 run only, or there are other models benefiting from it? If I look at the [PyTorch HUD](https://hud.pytorch.org/benchmark/torchbench/inductor_no_cudagraphs?startTime=Tue,%2023%20Jan%202024%2009:04:31%20GMT&stopTime=Tue,%2030%20Jan%202024%2009:04:31%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lBranch=main&lCommit=47b5a6b05d00e91182ee3c4a62f9b94e2d21b4eb&rBranch=main&rCommit=bb28965924cd142a9d12f475fa646c45acb8639f) it's not there.

**Comment by ysiraichi** [comment]
stable_diffusion benchmarks also depend on this token.
