### PR TITLE
Convert scalar to desired dtype before type promotion.

### LINKED ISSUE #1929: Seen floating point types of different precisions (...) but mixed precision is disallowed
## To Reproduce

```python
tpu = xm.xla_device()
m = nn.Linear(5, 10).to(device=tpu, dtype=torch.bfloat16)
x = torch.rand(8, 5).to(device=tpu, dtype=torch.bfloat16).requires_grad_(True)
x = m(x)
x *= 0.5  # <-- this line causes the exception
loss = x.sum()
loss.backward()
xm.mark_step()
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly 2020-04-16

### PR DESCRIPTION
**Pull request by ailzhang**
fixes #1929
I hit this problem in other places as well so took another look to fix. 
The root cause here is not pytorch call into (Tensor, Tensor) version of binary ops for scalar, since `at::result_type` correctly returns a dtype that doesn't consider scalar.  
The root cause is rather for all scalars we default its dtype to highest precision in the same category, e.g. in this case the scalar should really be `bfloat16` rather than `double`. This hurts because we do type promotion at in pytorch/xla which promotes to the higher one (while pytorch will know it's a scalar and doesn't promote).

### CODE REVIEW

File: torch_xla/csrc/aten_xla_type.cpp [hunk 1]
```diff
@@ -108,7 +108,9 @@ template <typename B>
 at::Tensor DoBinaryOp(const at::Tensor& self, const at::Tensor& other,
                       const B& bin_op) {
   at::ScalarType dtype = at::result_type(self, other);
-  std::pair<XLATensor, XLATensor> operands = GetBinaryOperands(self, other);
+  std::pair<XLATensor, XLATensor> operands = GetBinaryOperands(
+      self, other.unsafeGetTensorImpl()->is_wrapped_number() ? other.to(dtype)
```
Comment (dlibenzi) [inline torch_xla/csrc/aten_xla_type.cpp:112]: I'd put this "cloudy" code into a utility API in `torch_util.cpp` 😉 
Like:
```C++
at::Tensor UnwrapNumber(const at::Tensor& tensor, at::ScalarType dtype);
```
