### PR TITLE
Workaround at::scalar_tensor with BFloat16.

### LINKED ISSUE #2535: [PT_BREAK] value cannot be converted to type at::BFloat16 without overflow: -3.40282e+38
This is a failure in https://github.com/pytorch/pytorch/pull/45247:

```
Oct 06 20:13:12 ======================================================================
Oct 06 20:13:12 ERROR [0.005s]: test_clamp_max_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Oct 06 20:13:12 ----------------------------------------------------------------------
Oct 06 20:13:12 Traceback (most recent call last):
Oct 06 20:13:12   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
Oct 06 20:13:12     result = test_fn(self, *args)
Oct 06 20:13:12   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20477, in fn
Oct 06 20:13:12     device_result = getattr(device_tensor, op_str)(*device_args)
Oct 06 20:13:12 RuntimeError: value cannot be converted to type at::BFloat16 without overflow: -3.40282e+38
Oct 06 20:13:12 
Oct 06 20:13:12 ======================================================================
Oct 06 20:13:12 ERROR [0.005s]: test_clamp_min_inplace_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Oct 06 20:13:12 ----------------------------------------------------------------------
Oct 06 20:13:12 Traceback (most recent call last):
Oct 06 20:13:12   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
Oct 06 20:13:12     result = test_fn(self, *args)
Oct 06 20:13:12   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20477, in fn
Oct 06 20:13:12     device_result = getattr(device_tensor, op_str)(*device_args)
Oct 06 20:13:12 RuntimeError: value cannot be converted to type at::BFloat16 without overflow: 3.40282e+38
Oct 06 20:13:12 
Oct 06 20:13:12 ======================================================================
Oct 06 20:13:12 ERROR [0.005s]: test_clamp_min_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Oct 06 20:13:12 ----------------------------------------------------------------------
Oct 06 20:13:12 Traceback (most recent call last):
Oct 06 20:13:12   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
Oct 06 20:13:12     result = test_fn(self, *args)
Oct 06 20:13:12   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20477, in fn
Oct 06 20:13:12     device_result = getattr(device_tensor, op_str)(*device_args)
Oct 06 20:13:12 RuntimeError: value cannot be converted to type at::BFloat16 without overflow: 3.40282e+38
```

### PR DESCRIPTION
**Pull request by ailzhang**
fixes #2535

### CODE REVIEW

**Comment by cjolivier01** [comment]
Do you think this also affects normal float16, or is specifically related to bfloat16 using more bits for precision?

**Comment by ailzhang** [comment]
@cjolivier01 It might :P Since XLA doesn't support Half so it doesn't matter much here I think. I'll try to send a fix on pytorch side.

**Review by JackCaoG — APPROVED** [review]
Thanks!

File: torch_xla/csrc/tensor.cpp [hunk 1]
```diff
@@ -226,8 +226,13 @@ xla::ComputationClient::DataPtr GetDeviceData(const at::Tensor& tensor,
 xla::ComputationClient::DataPtr GetDeviceData(at::Scalar value,
                                               at::ScalarType scalar_type,
                                               const Device& device) {
-  return GetDeviceData(at::scalar_tensor(value, at::TensorOptions(scalar_type)),
-                       device);
+  // Workaround since at::scalar_tensor doesn't support bfloat16 yet.
```
Comment (davidel) [inline torch_xla/csrc/tensor.cpp:229]: This should be a utility function in torch_util.cpp/h, and a bug open with a reminder to remove the hack once scalar_tensor supports bfloat16.
Actually, it may be argued that this should be in pytorch main directly.

File: torch_xla/csrc/tensor.cpp [hunk 2]
```diff
@@ -226,8 +226,13 @@ xla::ComputationClient::DataPtr GetDeviceData(const at::Tensor& tensor,
...
+  at::Tensor t = at::scalar_tensor(
+      value, at::TensorOptions(scalar_type == at::ScalarType::BFloat16
+                                   ? at::ScalarType::Float
+                                   : scalar_type));
+  if (scalar_type == at::ScalarType::BFloat16) t = t.to(scalar_type);
```
Comment (davidel) [inline torch_xla/csrc/tensor.cpp:234]: This requires brackets around the single statement 😉
