### PR TITLE
Fix `global_device_map` sorting

### LINKED ISSUE #2601: xm.all_to_all working for TPU Pod ?
Hi, 

I am trying to learn how xm.all_to_all works on a TPU Pod (across multiple nodes).
I see examples using xmp.spawn to fork 1 or 8 processes on a node (xla/test/test_mp_all_to_all.py).
I assume torch_xla.distributed.xla_multiprocessing only work on a TPU node, not for POD, right ?
Is there an example of using xm.all_to_all on a POD, such as TPUv3-128 ?
Do I need to use cluster ? Thanks.

### PR DESCRIPTION
**Pull request by jysohn23**
Fixes #2601. Previously sorted lexicographically, causing wrong
DeviceAssignment and wrong result in `all_to_all` collective.

cc: @taylanbil

### CODE REVIEW

**Comment by taylanbil** [comment]
cc: @shz0116 you could try w/ tomorrow's nightly, it should resolve all_to_all bug on pods.

**Comment by shz0116** [comment]
> cc: @shz0116 you could try w/ tomorrow's nightly, it should resolve all_to_all bug on pods.

sure. thanks,

File: third_party/xla_client/xrt_computation_client.h [hunk 1]
```diff
@@ -114,22 +114,32 @@ class XrtComputationClient : public ComputationClient {
       return task_no == rhs.task_no && name == rhs.name;
     }
 
+    std::string ToString() const {
+      return name + ":" + std::to_string(task_no);
+    }
+
+    friend std::ostream& operator<<(std::ostream& stream,
+                                    const Worker& worker) {
+      stream << worker.name << ":" << worker.task_no;
```
Comment (JackCaoG) [inline third_party/xla_client/xrt_computation_client.h:123]: nit, 
```
stream << worker.ToString();
```

This way we only need to update one place when we want to change the worker string format.

File: third_party/xla_client/xrt_computation_client.h [hunk 2]
```diff
@@ -114,22 +114,32 @@ class XrtComputationClient : public ComputationClient {
...
     // (ie, /job:tpu_worker/replica:0/task:0/device:TPU:0), of the worker
     // exposing that device. These devices are all the devices present within
     // the TPU mesh.
-    std::map<std::string, std::string> global_device_map;
+    std::map<Worker, std::string> global_device_map;
     // These are the devices that this instance of PyTorch is handling. These
     // devices are in the form of "CPU:0", "TPU:3", ... For each of these
     // devices, there is an entry within the global_device_map.
-    std::set<std::string> devices;
+    std::set<string> devices;
```
Comment (JackCaoG) [inline third_party/xla_client/xrt_computation_client.h:142]: nit, let's keep it as `std::string` since the rest of the string in this file come with the explicit std namespace.

**Review by JackCaoG — CHANGES_REQUESTED** [review]
Thanks @jysohn23. Did you test this change with all_to_all test and see it passed on pod? Could trying out other mp test on pods to make sure we don't break other things( it shouldn't )?

File: third_party/xla_client/xrt_computation_client.h (hunk 1 above)
Comment (jysohn23) [reply third_party/xla_client/xrt_computation_client.h]: Thanks, done.

File: third_party/xla_client/xrt_computation_client.h (hunk 2 above)
Comment (jysohn23) [reply third_party/xla_client/xrt_computation_client.h]: Oops, didn't mean to change that.

**Comment by jysohn23** [comment]
Yes, I'd tested all_to_all on pods, but went ahead and tested all other tests with collectives as well.

**Review by JackCaoG — APPROVED** [review]
Thank!

File: third_party/xla_client/xrt_computation_client.h [hunk 3]
```diff
@@ -114,18 +114,28 @@ class XrtComputationClient : public ComputationClient {
...
   struct Options {
     std::string default_device;
-    // Maps a PyTorch device ID (example, "GPU:0", "TPU:0") to the full
+    // Maps a PyTorch Worker (example, {"GPU", 0}, {"TPU", 0}) to the full
     // coordinates in TF device format
     // (ie, /job:tpu_worker/replica:0/task:0/device:TPU:0), of the worker
     // exposing that device. These devices are all the devices present within
     // the TPU mesh.
-    std::map<std::string, std::string> global_device_map;
+    std::map<Worker, std::string> global_device_map;
```
Comment (davidel) [inline third_party/xla_client/xrt_computation_client.h:138]: This is not the correct fix.
The key should be the `Device` class defined at line 94, to which an `operator<()` should be added (as well as a `ToString()` and streaming `<<` eventually).
The key is a *Device* not a *Worker*.

**Review by davidel — CHANGES_REQUESTED** [review]

File: third_party/xla_client/xrt_computation_client.h (hunk 3 above)
Comment (jysohn23) [reply third_party/xla_client/xrt_computation_client.h]: Ah thanks for pointing out. I now see `Worker` is more of a TF worker concept it seems. I've updated to use `Device`.

**Review by davidel — COMMENTED** [review]
@jysohn23 So sorry to have sent you down the wrong path.
All the interfaces in XRT take `std::string` as data type, so I think we should leave the C++ APIs alone, and handle the proper sorting in `xla_model.py`:

https://github.com/pytorch/xla/blob/1f11dd7303ef0324a950a549e6ac44fed8211273/torch_xla/core/xla_model.py#L270

**Comment by jysohn23** [comment]
> @jysohn23 So sorry to have sent you down the wrong path.
> All the interfaces in XRT take `std::string` as data type, so I think we should leave the C++ APIs alone, and handle the proper sorting in `xla_model.py`:
> 
> https://github.com/pytorch/xla/blob/1f11dd7303ef0324a950a549e6ac44fed8211273/torch_xla/core/xla_model.py#L270

No worries. Updated to handle at the Python setup level.

**Review by davidel — APPROVED** [review]
Thanks @jysohn23 !
