### PR TITLE
Re-install `torchvision` when updating wheels

### LINKED ISSUE #905: pytorch-nightly torchvision error
I just updated my pytorch-nightly conda environment, and tried to run a script to train a model that was working previously. The error I received is pasted below:

`Traceback (most recent call last):
  File "test_train_cifar.py", line 20, in <module>
    import torchvision
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/__init__.py", line 1, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/models/__init__.py", line 11, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/models/detection/__init__.py", line 1, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/ops/__init__.py", line 1, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py", line 2, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/_C.py", line 7, in <module>
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/_C.py", line 6, in __bootstrap__
  File "/anaconda3/envs/pytorch-nightly/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/jupyter/.cache/Python-Eggs/torchvision-0.3.0-py3.6-linux-x86_64.egg-tmp/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariable_Wrap`

### PR DESCRIPTION
**Pull request by jysohn23**
Fixed #905

### CODE REVIEW

File: scripts/update_nightly_torch_wheels.sh [hunk 1]
```diff
@@ -17,3 +17,13 @@ pip install "/tmp/$TORCH_WHEEL"
 pip install "/tmp/$TORCH_XLA_WHEEL"
 
 rm -f "/tmp/$TORCH_WHEEL" "/tmp/$TORCH_XLA_WHEEL"
+
```
Comment (dlibenzi) [inline scripts/update_nightly_torch_wheels.sh]: Maybe put this in a function?

Comment (jysohn23) [reply scripts/update_nightly_torch_wheels.sh]: Done.
