### PR TITLE
Fix multi-index operation which starts with null indices

### LINKED ISSUE #608: empty ndim index
```
import torch
import torch_xla
import torch_xla_py.utils as xu
import torch_xla_py.xla_model as xm
import pdb
import torch.nn.functional as F
xla_device = xm.xla_device()
xla_device = 'cpu'
v = torch.randn(2, 3, 4, 5).to(xla_device)
a = torch.empty(2, 0, 6, 4, 5, device=xla_device)
b = v[:, torch.empty(0, 6, dtype=torch.int64, device=xla_device)]
pdb.set_trace()
print(a.shape)
print(b.shape)
```
Got 
```
torch.Size([2, 0, 6, 4, 5])
torch.Size([0, 6, 2, 4, 5])
```
Expect:
```
torch.Size([2, 0, 6, 4, 5])
torch.Size([2, 0, 6, 4, 5])
```

### PR DESCRIPTION
**Pull request by asuhan**
Fixes #608.

### CODE REVIEW

File: torch_xla/csrc/ops/index_ops.cpp [hunk 1]
```diff
@@ -58,6 +60,21 @@ std::vector<at::Tensor> ExpandByteTensors(const at::Tensor& self,
   return result;
 }
 
+struct IndexAdjacencyInfo {
+  bool contiguous_non_null;
```
Comment (dlibenzi) [inline torch_xla/csrc/ops/index_ops.cpp]: Init to avoid garbage in case someone instantiate this with default ctor.

File: torch_xla/csrc/ops/index_ops.cpp [hunk 2]
```diff
@@ -58,6 +60,21 @@ std::vector<at::Tensor> ExpandByteTensors(const at::Tensor& self,
...
+  xla::int64 start_dim;
+};
+
+IndexAdjacencyInfo GetIndexAdjacencyInfo(at::TensorList indices) {
```
Comment (dlibenzi) [inline torch_xla/csrc/ops/index_ops.cpp]: Small comment would help.

Comment (dlibenzi) [reply torch_xla/csrc/ops/index_ops.cpp]: Also, mentioning the aten source this is coming from, can speed up the review.

File: torch_xla/csrc/ops/index_ops.h [hunk 3]
```diff
@@ -37,6 +37,8 @@ struct CanonicalIndexInfo {
   // updates, since a permutation is applied to the base to bring non-null
   // indices to front. This is the inverse of that permutation.
   std::vector<xla::int64> result_permutation;
+  // The dimension number at which indexing starts.
+  xla::int64 start_dim;
```
Comment (dlibenzi) [inline torch_xla/csrc/ops/index_ops.h]: Init

File: torch_xla/csrc/xla_lower_util.cpp [hunk 4]
```diff
@@ -315,21 +316,34 @@ xla::XlaOp CreateIndex(const xla::XlaOp& input, const xla::XlaOp& indices) {
...
-      dim_numbers.add_offset_dims(i + indices_rank - num_index_dims);
+      dim_numbers.add_offset_dims(i - num_index_dims + indices_rank);
     }
   }
   dim_numbers.set_index_vector_dim(indices_shape.rank() - 1);
   for (xla::int64 i = 0; i < num_index_dims; i++) {
     dim_numbers.add_start_index_map(i);
   }
-  return xla::Gather(input, indices, dim_numbers, slice_sizes);
+  xla::XlaOp gathered = xla::Gather(input, indices, dim_numbers, slice_sizes);
```
Comment (dlibenzi) [inline torch_xla/csrc/xla_lower_util.cpp]: In these case I think it is more readable like:
```
result = foo(...);
if (cond) {
  ...
  result = moo(...);
}
return result;
```

File: torch_xla/csrc/ops/index_get.cpp [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+  };
+  return InferOutputShape({base.shape(), indices.shape()}, lower_for_shape_fn);
+}
+
+}  // namespace
+
+IndexGet::IndexGet(const ir::Value& base, const ir::Value& indices,
+                   xla::int64 start_dim)
+    : Node(
+          OpKind(at::aten::index), {base, indices},
```
Comment (dlibenzi) [inline torch_xla/csrc/ops/index_get.cpp]: Is this really `aten::index` or should be `xla::index_get`?

File: torch_xla/csrc/ops/index_ops.cpp (hunk 1 above)
Comment (asuhan) [reply torch_xla/csrc/ops/index_ops.cpp]: Done.

File: torch_xla/csrc/ops/index_ops.cpp (hunk 2 above)
Comment (asuhan) [reply torch_xla/csrc/ops/index_ops.cpp]: Done.

File: torch_xla/csrc/ops/index_ops.h (hunk 3 above)
Comment (asuhan) [reply torch_xla/csrc/ops/index_ops.h]: Done.

File: torch_xla/csrc/ops/index_get.cpp (hunk 5 above)
Comment (asuhan) [reply torch_xla/csrc/ops/index_get.cpp]: It's `aten::index`, the other indexing operations have dedicated names (`index_select`, `index_put` etc). I like `IndexGet` better as a name, but we do have an ATen symbol.

File: torch_xla/csrc/xla_lower_util.cpp (hunk 4 above)
Comment (asuhan) [reply torch_xla/csrc/xla_lower_util.cpp]: Done it with just a `Gather`, we can avoid the permute by making good use of `start_index_map`.
